apiVersion: apps/v1
kind: Deploymnet
metadata:
  name: gateway-deploy
  labels:
    name: gateway-deploy
    app: microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
      type: microservice
  template:
    metadata:
      name: gateway-pod
      labels:
        app: gateway
        type: microservice
    spec:
      containers:
        - name: gateway-app
          image: nicolasundiano/serviciosapigateway:latest
          ports:
            - containerPort: 80